### ISSUE TITLE
Change the package laminas-console with laminas-mvc-console

### ISSUE THREAD

**Issue by juizmill** [laminas/laminas-test#16]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | yes

Change the package  [laminas-console](https://github.com/laminas/laminas-console/)  with  [laminas-mvc-console](https://github.com/laminas/laminas-mvc-console)

With this change we can make the laminas-test package compatible with **PHP 8** #15 

Reference in the composer:  https://github.com/laminas/laminas-test/blob/3.5.x/composer.json#L25

**Comment by froschdesign** [comment]
@juizmill 
laminas-mvc-console depends on laminas-console and both are deprecated.

* https://github.com/laminas/laminas-mvc-console/blob/90338c7b61a5fa8445c0a41925a4ae351459fa79/composer.json#L34
* https://docs.laminas.dev/laminas-mvc-console/

> With this change we can make the laminas-test package compatible with PHP 8 #15

I think this would not work. laminas-console is not compatible with PHP 8 and the checks via Composer [ignores all platform requirements](https://github.com/laminas/laminas-mvc-console/blob/90338c7b61a5fa8445c0a41925a4ae351459fa79/.travis.yml#L29-L36).

**Comment by juizmill** [comment]
@froschdesign that's why I removed this PR #17

**Comment by froschdesign** [comment]
@juizmill 
It does not help because both packages are deprecated, laminas-mvc-console and on laminas-console.

**Comment by froschdesign** [comment]
The laminas-console support must also be marked as deprecated in this component and removed later.

**Comment by juizmill** [comment]
I am having trouble installing laminas-skeleton with PHP 8, due to these packages. Do you have any suggestions?

**Comment by froschdesign** [comment]
> I am having trouble installing laminas-skeleton with PHP 8, due to these packages. Do you have any suggestions?

Correct, this is unfortunately a problem. As workaround, skip laminas-test during the installation.

**Comment by juizmill** [comment]
OK .. anyway i am available to help!

**Comment by steffendietz** [comment]
Is there any plan to release version `4` of `laminas/laminas-test`? The end of active support for all versions of `php 7` is approaching fast, and with dependencies for this package abandoned and not ready for `php 8`, we're currently sitting in a strange spot.

Would it make sense to lift the `archived` status of the dependencies and support `php 8` with them, until the release management of the dependent packages has been sorted out?

Poking around a little there apparently was a [project](https://github.com/orgs/laminas/projects/11) regarding `php 8` support, but that was marked as `closed` by @froschdesign in mid august. - Do I miss something here?

**Comment by froschdesign** [comment]
@steffendietz 
> Would it make sense to lift the `archived` status of the dependencies and support `php 8` with them, until the release management of the dependent packages has been sorted out?

The entire support for the console (via laminas-console and laminas-mvc-console) must be removed from laminas-test. No need for new versions on obsolete packages.

Any help is welcome! 👍

**Comment by steffendietz** [comment]
I understand and completely agree with the long-term goal. But currently `laminas/laminas-test` (and other `laminas` packages, looking at you, `laminas/laminas-cache`) is not installable under `php8`.
So it seems to me abandoning packages, without having released replacements, might have been a bit premature. Especially since `laminas` is a _live_ product.

> No need for new versions on obsolete packages.

I feel the argument is a bit reversed. Without released alternatives to point to, there absolutely **is** a need for them to be still installable. Else peoples installations ~~will break~~ are currently breaking when updating PHP.

I would absolutely understand not supporting packages any more if there was an alternative.

> Any help is welcome! :+1: 

Is there a place I can have a look what is still needed for a `4.0` release of `laminas/laminas-test`? The [milestone](https://github.com/laminas/laminas-test/milestone/5) currently has no open issues.

**Comment by froschdesign** [comment]
@steffendietz 
> …and other `laminas` packages, looking at you, `laminas/laminas-cache`) is not installable under `php8`.

Unfortunately you have missed something: https://github.com/laminas/laminas-cache/releases/tag/2.11.0

**Comment by steffendietz** [comment]
> Unfortunately you have missed something: https://github.com/laminas/laminas-cache/releases/tag/2.11.0

Unfortunately, I have not.

`laminas/laminas-cache:2.11.0`, while supporting `php8`, has a dependency on various `adapter` packages (e.g. `laminas/laminas-cache-storage-adapter-apc`) which are abandoned and don't support `php8`. So, in essence, the situation there is comparable to this package here, really.

While `laminas/laminas-cache:3.5.0` itself supports `php8`, it has dependencies on other `laminas` packages which do not.

It's basically my whole point.

**Comment by froschdesign** [comment]
> …has a dependency on various `adapter` packages (e.g. `laminas/laminas-cache-storage-adapter-apc`) which are abandoned and don't support `php8`.

The apc adapter can never support PHP 8 because the underlying PHP extension is outdated. Use laminas-cache-storage-adapter-apcu instead and follow the installation instructions:

https://docs.laminas.dev/laminas-cache/installation/#avoid-unused-cache-adapters-are-being-installed

**Comment by froschdesign** [comment]
Back to topic and the current issue:

The original issue report for PHP8 support (#15) is already closed. If there are still problems with the installation and PHP 8 then we need a concrete bug report or better a pull request to fix the problem.

laminas-console and laminas-mvc-console should be removed because these packages are obsolete.

As current workaround, laminas-console can be added to the `replace` section in the Composer configuration file of your application.

**Comment by steffendietz** [comment]
> Back to topic and the current issue

Yes, please.

> laminas-console and laminas-mvc-console should be removed because these packages are obsolete.

The current `4.0.x` branch has already dropped the dependencies for `laminas/laminas-console` and, as this issue here is also concerned with removing said package from the dependencies to let the `php8` compatibility come into effect, I thought here would be a good place to ask what the status of the `4.0` release is.

So:

* the `4.0.x` branch has dropped dependencies on `laminas/laminas-console`
* the `4.0` milestone has no open issues

So, what's left to do for a `4.0` release, so that I could prevent the introduction of workarounds into my package?

Thank you, for your support.

**Comment by steffendietz** [comment]
PR which dropped `laminas/laminas-console`: #32

**Comment by froschdesign** [comment]
> The current `4.0.x` branch has already dropped the dependencies for `laminas/laminas-console`

Great!

> So, what's left to do for a `4.0` release…

Bug fixing, which means that version 3.5.2 will be released first.
Everyone can help on the current open pull requests: https://github.com/laminas/laminas-test/pulls

**Comment by snapshotpl** [comment]
Fixed by #32
